apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: argo-pipeline-app
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-branch
    default: main
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-pipeline-$(tt.params.git-repo-name)-$(tt.params.git-branch)
    spec:
      serviceAccountName: pipeline-account
      pipelineRef:
        name: build-pipeline
      params:
      - name: gitUrl
        value: $(tt.params.git-repo-url)
      - name: gitRevision
        value: $(tt.params.git-revision)
      - name: gitBranch
        value: $(tt.parmas.git-branch)
      - name: imageUrl
        value: us.icr.io/argo-pipeline/web
      workspaces:
      - name: git-source
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Mi