apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ich-www
  name: ich-www
  namespace: ich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ich-www
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ich-www
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        image: us.icr.io/ich/ich-www
        name: ich-www
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: all-icr-io
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ich-www
  name: ich-www-service
  namespace: ich
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31228
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    nodePort: 30771
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ich-www
  sessionAffinity: None
  type: LoadBalancer
